# Generated by Django 3.2 on 2021-08-11 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PrankList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourName', models.CharField(max_length=50)),
                ('crushName', models.CharField(max_length=50)),
                ('prankster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prankster_name', to='crush.createuser')),
            ],
        ),
    ]
